### ISSUE TITLE
Qwen3.5-122B-A10B-JANG_2S fails first forward pass with gather_qmm shape mismatch on vMLX 1.6.64

### ISSUE THREAD

**Issue by gajsanders** [jjang-ai/vmlx#280]
# Qwen3.5-122B-A10B-JANG_2S fails first forward pass with gather_qmm shape mismatch on vMLX 1.6.64

## Summary

`JANGQ-AI/Qwen3.5-122B-A10B-JANG_2S` loads successfully in vMLX 1.6.64, but the first text-generation forward pass fails with a `gather_qmm` shape mismatch.

The model passes config/weight/architecture checks and loads as a JANG v2 VLM, but generation fails before producing any tokens.

## Environment

- Hardware: Apple M4 Max
- Unified memory: 128 GB
- macOS: 26.6.2 (25G83)
- Architecture: arm64
- vMLX: 1.6.64
- Bundled `vmlx_engine`: 1.6.64
- Model: `JANGQ-AI/Qwen3.5-122B-A10B-JANG_2S`

Standalone JANG test environment:

- Python: 3.12.13
- jang: 2.5.47
- mlx: 0.32.2
- mlx-lm: 0.31.3
- mlx-vlm: 0.7.2
- transformers: 5.17.0

## Model validation

`vmlx info` reports:

```text
Architecture: Qwen3_5MoeForConditionalGeneration (qwen3_5_moe)
Layers: 48
Hidden size: 3072
Vocab size: 248,320
Quantization: JANG 2.1-bit mixed-precision (block_size=128)
Multimodal: Yes (vision)
Weight files: 8 (35.2 GB)
```

`vmlx doctor` successfully passes:

- Config
- Weight loading
- Architecture detection

The model is detected as JANG v2 and loads via mmap.

During a normal serve run, vMLX reports:

```text
Pre-fixed 421 module(s) with mixed-precision bit widths
Wired limit set to 55 GB (model 38 GB)
JANG v2 VLM loaded in 3.0s
JANG VL model loaded
SimpleEngine loaded
Metal GPU memory after load: 34.46GB active
Application startup complete
```

So model loading itself appears successful.

## Reproduction

Serve command:

```bash
vmlx serve \
  "$HOME/Models/JANG/Qwen3.5-122B-A10B-JANG_2S" \
  --host 127.0.0.1 \
  --port 8000 \
  --max-prompt-tokens 65536 \
  --no-continuous-batching \
  --disable-native-mtp \
  --reasoning-parser none \
  --default-temperature 0.3 \
  --default-top-p 0.8 \
  --default-top-k 40 \
  --default-repetition-penalty 1.1 \
  --default-enable-thinking false
```

Then:

```bash
curl -s http://127.0.0.1:8000/v1/chat/completions \
  -H 'Content-Type: application/json' \
  -d '{
    "model": "Qwen3.5-122B-A10B-JANG_2S",
    "messages": [
      {
        "role": "user",
        "content": "Write a Python function that returns the nth Fibonacci number. Be concise."
      }
    ],
    "temperature": 0.3,
    "top_p": 0.8,
    "max_tokens": 128
  }'
```

## Actual result

The request fails with:

```text
[gather_qmm] Last dimension of first input with shape (..., 3072)
does not match the expanded quantized matrix (768, 1024)
computed from shape (256,1024,192)
with group_size=32, bits=8 and transpose=true
```

This happens with native MTP disabled as well.

## Relevant tensor shapes in the bundle

Inspecting the safetensors shows the 256-expert `switch_mlp` tensors are consistently packed like this:

```text
model.language_model.layers.N.mlp.switch_mlp.gate_proj.weight
  (256, 1024, 192)

model.language_model.layers.N.mlp.switch_mlp.gate_proj.scales
  (256, 1024, 24)

model.language_model.layers.N.mlp.switch_mlp.gate_proj.biases
  (256, 1024, 24)

model.language_model.layers.N.mlp.switch_mlp.up_proj.weight
  (256, 1024, 192)

model.language_model.layers.N.mlp.switch_mlp.up_proj.scales
  (256, 1024, 24)
```

`down_proj` tensors are consistently:

```text
model.language_model.layers.N.mlp.switch_mlp.down_proj.weight
  (256, 3072, 64)

model.language_model.layers.N.mlp.switch_mlp.down_proj.scales
  (256, 3072, 8)

model.language_model.layers.N.mlp.switch_mlp.down_proj.biases
  (256, 3072, 8)
```

The runtime error appears to interpret a `(256, 1024, 192)` expert tensor using:

```text
group_size=32
bits=8
```

which seems inconsistent with how these tensors are actually packed.

## Possible clue

The JANG loader logs show mixed-precision pre-fixing for modules such as:

```text
language_model.model.layers.N.mlp.shared_expert.gate_proj
language_model.model.layers.N.mlp.shared_expert.up_proj
language_model.model.layers.N.mlp.gate
```

but the main expert tensors in the artifact are named:

```text
model.language_model.layers.N.mlp.switch_mlp.gate_proj
model.language_model.layers.N.mlp.switch_mlp.up_proj
model.language_model.layers.N.mlp.switch_mlp.down_proj
```

This makes me wonder whether the `switch_mlp` expert modules are not receiving the intended per-tensor JANG bit-width/group-size metadata and are falling back to a default `8-bit / group_size=32` interpretation.

## MTP-related behavior

Initially, `vmlx doctor` also failed while native MTP was active on:

```text
language_model.mtp.layers.0.mlp.experts.0.gate_proj.weight
```

Disabling native MTP allowed the server to start, but the same `gather_qmm` shape mismatch then occurred during normal text generation.

The bundle contains MTP `switch_mlp` tensors in the same packed format:

```text
mtp.layers.0.mlp.switch_mlp.gate_proj.weight
  (256, 1024, 192)

mtp.layers.0.mlp.switch_mlp.down_proj.weight
  (256, 3072, 64)
```

so the MTP failure may be related to the same metadata/layout issue.

## Standalone JANG test

I also tested the bundle with `jang==2.5.47` directly.

The bundle loads successfully, but generation is currently blocked earlier by an `mlx-vlm` / `mlx-lm` Qwen3.5 cache API mismatch:

```text
TypeError: create_attention_mask() missing 2 required positional arguments:
'return_array' and 'window_size'
```

So I have not yet been able to determine whether standalone JANG reaches the same `gather_qmm` failure.

## Expected result

The model should complete a normal text-only forward pass and generate tokens.

## Questions

1. Is `Qwen3.5-122B-A10B-JANG_2S` expected to work with vMLX 1.6.64?
2. Could the `switch_mlp` expert modules be missing per-tensor JANG quantization metadata during hydration?
3. Is there a newer bundle or runtime patch I should test?
4. Is the `bits=8, group_size=32` interpretation of the `(256,1024,192)` tensor expected for this artifact?

[qwen122-jang-vmlx-debug-sanitized.log](https://github.com/user-attachments/files/32576794/qwen122-jang-vmlx-debug-sanitized.log)
